/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import digitalnipotpissifrovanje.DigitalniPotpis;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Cmiloje
 */
public class DigitalnoPotpisivanje extends javax.swing.JDialog {

    /**
     * Creates new form DigitalnoPotpisivanje
     */
    public static String signAlg = "";
    
    public DigitalnoPotpisivanje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sertifikatAlias_TF = new javax.swing.JTextField();
        izaberiSertifikat_B = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fajl_TF = new javax.swing.JTextField();
        izaberiFajl_B = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lokacijaPotpisa_TF = new javax.swing.JTextField();
        lokacijaPotpisa_B = new javax.swing.JButton();
        potpisi_B = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digitalno potpisivanje");

        jLabel1.setText("Izaberite sertifikat sa kojim želite da potpišete:");

        sertifikatAlias_TF.setEditable(false);

        izaberiSertifikat_B.setText("...");
        izaberiSertifikat_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izaberiSertifikat_BActionPerformed(evt);
            }
        });

        jLabel2.setText("Izaberite fajl koji želite da potpišete:");

        fajl_TF.setEditable(false);

        izaberiFajl_B.setText("...");
        izaberiFajl_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izaberiFajl_BActionPerformed(evt);
            }
        });

        jLabel3.setText("Izaberite lokaciju gdje želite da sačuvate vaš potpis:");

        lokacijaPotpisa_TF.setEditable(false);

        lokacijaPotpisa_B.setText("...");
        lokacijaPotpisa_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokacijaPotpisa_BActionPerformed(evt);
            }
        });

        potpisi_B.setText("POTPISI");
        potpisi_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potpisi_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(potpisi_B)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(sertifikatAlias_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(izaberiSertifikat_B))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fajl_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(izaberiFajl_B))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lokacijaPotpisa_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lokacijaPotpisa_B))))
                .addGap(30, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sertifikatAlias_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izaberiSertifikat_B))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fajl_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izaberiFajl_B))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lokacijaPotpisa_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lokacijaPotpisa_B))
                .addGap(18, 18, 18)
                .addComponent(potpisi_B)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izaberiSertifikat_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izaberiSertifikat_BActionPerformed
        PregledSertifikataDialog psd = new PregledSertifikataDialog(null, true);
        psd.setLocationRelativeTo(null);
        psd.setVisible(true);
    }//GEN-LAST:event_izaberiSertifikat_BActionPerformed

    private void izaberiFajl_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izaberiFajl_BActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Izaberite fajl koji zelite da potpisete");
        int opcija = jfc.showDialog(null, "Izaberi");
        if(opcija == JFileChooser.APPROVE_OPTION){
            this.fajl_TF.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_izaberiFajl_BActionPerformed

    private void lokacijaPotpisa_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokacijaPotpisa_BActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Izaberite lokaciju za snimanje digitalnog potpisa");
        int opcija = jfc.showDialog(null, "Izaberi");
        if(opcija == JFileChooser.APPROVE_OPTION){
            this.lokacijaPotpisa_TF.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_lokacijaPotpisa_BActionPerformed

    private void potpisi_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potpisi_BActionPerformed
        DigitalniPotpis dp = new DigitalniPotpis();
        try {
            System.out.println("SIGN: "+this.getSignAlg());
            dp.Potpisi(this.sertifikatAlias_TF.getText(), this.getSignAlg(), this.fajl_TF.getText(), this.lokacijaPotpisa_TF.getText());
            JOptionPane.showMessageDialog(null, "Uspjesno potpisivanje", "Info...", JOptionPane.INFORMATION_MESSAGE);
        } catch (KeyStoreException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CertificateException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnrecoverableKeyException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SignatureException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_potpisi_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalnoPotpisivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DigitalnoPotpisivanje dialog = new DigitalnoPotpisivanje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public static String getSignAlg() {
        return signAlg;
    }

    public static void setSignAlg(String signAlg) {
        DigitalnoPotpisivanje.signAlg = signAlg;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fajl_TF;
    private javax.swing.JButton izaberiFajl_B;
    private javax.swing.JButton izaberiSertifikat_B;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lokacijaPotpisa_B;
    private javax.swing.JTextField lokacijaPotpisa_TF;
    private javax.swing.JButton potpisi_B;
    public static javax.swing.JTextField sertifikatAlias_TF;
    // End of variables declaration//GEN-END:variables
}
