/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cmd.SkladisteKljucevaSertifikata;
import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Cmiloje
 */
public class GlavniEkran extends javax.swing.JFrame {

    /**
     * Creates new form izaberiOperacije
     */
    SkladisteKljucevaSertifikata sks;
    
    public GlavniEkran() {
        initComponents();
        try {
            sks = new SkladisteKljucevaSertifikata();
        } catch (KeyStoreException ex) {
            Logger.getLogger(GlavniEkran.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GlavniEkran.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(GlavniEkran.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CertificateException ex) {
            Logger.getLogger(GlavniEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prikaz_PANEL = new javax.swing.JPanel();
        digitalnoPotpis_PANEL = new javax.swing.JPanel();
        dugme_B = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        verifijPotpis_PANEL = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        verifikujPotpis_B = new javax.swing.JButton();
        moj_MENIBAR = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        generisiSertifikat_MI = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        pregledSertifikata_MI = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        potpisi_MI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        verifikujPotpis_MI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRI - Sinergija");

        digitalnoPotpis_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitalno potpiši fajl"));
        digitalnoPotpis_PANEL.setPreferredSize(new java.awt.Dimension(140, 140));

        dugme_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_file.png"))); // NOI18N
        dugme_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugme_BActionPerformed(evt);
            }
        });

        jLabel7.setText("Izaberite fajl:");

        javax.swing.GroupLayout digitalnoPotpis_PANELLayout = new javax.swing.GroupLayout(digitalnoPotpis_PANEL);
        digitalnoPotpis_PANEL.setLayout(digitalnoPotpis_PANELLayout);
        digitalnoPotpis_PANELLayout.setHorizontalGroup(
            digitalnoPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitalnoPotpis_PANELLayout.createSequentialGroup()
                .addGroup(digitalnoPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(digitalnoPotpis_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(digitalnoPotpis_PANELLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(dugme_B, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        digitalnoPotpis_PANELLayout.setVerticalGroup(
            digitalnoPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitalnoPotpis_PANELLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dugme_B)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        verifijPotpis_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder("Verifikuj digitalni potpis"));

        jLabel9.setText("Izaberite fajl:");

        verifikujPotpis_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_file.png"))); // NOI18N
        verifikujPotpis_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikujPotpis_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verifijPotpis_PANELLayout = new javax.swing.GroupLayout(verifijPotpis_PANEL);
        verifijPotpis_PANEL.setLayout(verifijPotpis_PANELLayout);
        verifijPotpis_PANELLayout.setHorizontalGroup(
            verifijPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifijPotpis_PANELLayout.createSequentialGroup()
                .addGroup(verifijPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verifijPotpis_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(verifijPotpis_PANELLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(verifikujPotpis_B, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        verifijPotpis_PANELLayout.setVerticalGroup(
            verifijPotpis_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifijPotpis_PANELLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verifikujPotpis_B)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout prikaz_PANELLayout = new javax.swing.GroupLayout(prikaz_PANEL);
        prikaz_PANEL.setLayout(prikaz_PANELLayout);
        prikaz_PANELLayout.setHorizontalGroup(
            prikaz_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prikaz_PANELLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(digitalnoPotpis_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(verifijPotpis_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        prikaz_PANELLayout.setVerticalGroup(
            prikaz_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prikaz_PANELLayout.createSequentialGroup()
                .addGroup(prikaz_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(prikaz_PANELLayout.createSequentialGroup()
                        .addGroup(prikaz_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(prikaz_PANELLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(verifijPotpis_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(prikaz_PANELLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(digitalnoPotpis_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("App");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stop.png"))); // NOI18N
        jMenuItem1.setText("Izlaz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        moj_MENIBAR.add(jMenu1);

        jMenu2.setText("Sertifikati");

        generisiSertifikat_MI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        generisiSertifikat_MI.setText("Generiši");
        generisiSertifikat_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generisiSertifikat_MIActionPerformed(evt);
            }
        });
        jMenu2.add(generisiSertifikat_MI);
        jMenu2.add(jSeparator2);

        pregledSertifikata_MI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier.png"))); // NOI18N
        pregledSertifikata_MI.setText("Pregled");
        pregledSertifikata_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregledSertifikata_MIActionPerformed(evt);
            }
        });
        jMenu2.add(pregledSertifikata_MI);

        moj_MENIBAR.add(jMenu2);

        jMenu3.setText("Digitalni potpis");

        potpisi_MI.setText("Potpiši");
        potpisi_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potpisi_MIActionPerformed(evt);
            }
        });
        jMenu3.add(potpisi_MI);
        jMenu3.add(jSeparator1);

        verifikujPotpis_MI.setText("Verifikuj");
        verifikujPotpis_MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikujPotpis_MIActionPerformed(evt);
            }
        });
        jMenu3.add(verifikujPotpis_MI);

        moj_MENIBAR.add(jMenu3);

        setJMenuBar(moj_MENIBAR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prikaz_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prikaz_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void generisiSertifikat_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generisiSertifikat_MIActionPerformed
        GenerisiSertifikat gs = new GenerisiSertifikat(this, true);
        gs.setLocationRelativeTo(null);
        gs.setVisible(true);
    }//GEN-LAST:event_generisiSertifikat_MIActionPerformed

    private void pregledSertifikata_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregledSertifikata_MIActionPerformed
        PregledSertifikataDialog psd = new PregledSertifikataDialog(this, true);
        psd.setLocationRelativeTo(null);
        psd.setVisible(true);
    }//GEN-LAST:event_pregledSertifikata_MIActionPerformed

    private void dugme_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugme_BActionPerformed
        DigitalnoPotpisivanje dp = new DigitalnoPotpisivanje(this, true);
        dp.setLocationRelativeTo(null);
        dp.setVisible(true);
    }//GEN-LAST:event_dugme_BActionPerformed

    private void potpisi_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potpisi_MIActionPerformed
        DigitalnoPotpisivanje dp = new DigitalnoPotpisivanje(this, true);
        dp.setLocationRelativeTo(null);
        dp.setVisible(true);
    }//GEN-LAST:event_potpisi_MIActionPerformed

    private void verifikujPotpis_MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikujPotpis_MIActionPerformed
        VerifikovanjeDigitalnogPotpisa vdp = new VerifikovanjeDigitalnogPotpisa(this, true);
        vdp.setLocationRelativeTo(null);
        vdp.setVisible(true);
    }//GEN-LAST:event_verifikujPotpis_MIActionPerformed

    private void verifikujPotpis_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikujPotpis_BActionPerformed
        VerifikovanjeDigitalnogPotpisa vdp = new VerifikovanjeDigitalnogPotpisa(this, true);
        vdp.setLocationRelativeTo(null);
        vdp.setVisible(true);
    }//GEN-LAST:event_verifikujPotpis_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GlavniEkran ge = new GlavniEkran();
                ge.setLocationRelativeTo(null);
                ge.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel digitalnoPotpis_PANEL;
    private javax.swing.JButton dugme_B;
    private javax.swing.JMenuItem generisiSertifikat_MI;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuBar moj_MENIBAR;
    private javax.swing.JMenuItem potpisi_MI;
    private javax.swing.JMenuItem pregledSertifikata_MI;
    private javax.swing.JPanel prikaz_PANEL;
    private javax.swing.JPanel verifijPotpis_PANEL;
    private javax.swing.JButton verifikujPotpis_B;
    private javax.swing.JMenuItem verifikujPotpis_MI;
    // End of variables declaration//GEN-END:variables
}
