/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import digitalnipotpissifrovanje.DigitalniPotpis;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.security.cert.CertificateException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Cmiloje
 */
public class VerifikovanjeDigitalnogPotpisa extends javax.swing.JDialog {

    /**
     * Creates new form VerifikovanjeDigitalnogPotpisa
     */
    public VerifikovanjeDigitalnogPotpisa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sertifikat_TF = new javax.swing.JTextField();
        izaberiSertifikat_B = new javax.swing.JButton();
        potpis_TF = new javax.swing.JTextField();
        izaberiPotpis_B = new javax.swing.JButton();
        faj_TF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        verifikuj_B = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verifikacija digitalnog potpisa");

        jLabel1.setText("Izaberite sertifikat sa kojim želite da verifikujete potpis:");

        jLabel2.setText("Izaberite digitalni potpis za verifikaciju:");

        jLabel3.setText("Izaberite fajl za verifikaciju:");

        sertifikat_TF.setEditable(false);

        izaberiSertifikat_B.setText("...");
        izaberiSertifikat_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izaberiSertifikat_BActionPerformed(evt);
            }
        });

        potpis_TF.setEditable(false);

        izaberiPotpis_B.setText("...");
        izaberiPotpis_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izaberiPotpis_BActionPerformed(evt);
            }
        });

        faj_TF.setEditable(false);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        verifikuj_B.setText("VERIFIKUJ");
        verifikuj_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikuj_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verifikuj_B)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sertifikat_TF)
                            .addComponent(potpis_TF)
                            .addComponent(faj_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(izaberiSertifikat_B)
                            .addComponent(izaberiPotpis_B)
                            .addComponent(jButton1))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sertifikat_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izaberiSertifikat_B))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(potpis_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izaberiPotpis_B))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(faj_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(verifikuj_B)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izaberiSertifikat_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izaberiSertifikat_BActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Izaberite sertifikat sa kojim zelite da verifikujete potpis");
        int opcija = jfc.showDialog(null, "Izaberi");
        if(opcija == JFileChooser.APPROVE_OPTION){
            this.sertifikat_TF.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_izaberiSertifikat_BActionPerformed

    private void izaberiPotpis_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izaberiPotpis_BActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Izaberite potpis za verifikaciju...");
        int opcija = jfc.showDialog(null, "Izaberi");
        if(opcija == JFileChooser.APPROVE_OPTION){
            this.potpis_TF.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_izaberiPotpis_BActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Izaberite fajl za verifikaciju...");
        int opcija = jfc.showDialog(null, "Izaberi");
        if(opcija == JFileChooser.APPROVE_OPTION){
            this.faj_TF.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verifikuj_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikuj_BActionPerformed
        DigitalniPotpis dp = new DigitalniPotpis();
        try {
            dp.provjeriDigitalniPotpis(this.sertifikat_TF.getText(), this.potpis_TF.getText(), this.faj_TF.getText());
        } catch (CertificateException ex) {
            Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SignatureException ex) {
            Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifikuj_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifikovanjeDigitalnogPotpisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerifikovanjeDigitalnogPotpisa dialog = new VerifikovanjeDigitalnogPotpisa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField faj_TF;
    private javax.swing.JButton izaberiPotpis_B;
    private javax.swing.JButton izaberiSertifikat_B;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField potpis_TF;
    private javax.swing.JTextField sertifikat_TF;
    private javax.swing.JButton verifikuj_B;
    // End of variables declaration//GEN-END:variables
}
